name: compass_app
description: A modern compass app built with Flutter.
version: 0.1.0+1
publish_to: "none"
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: any
  permission_handler: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # no assets required by default
